### ISSUE TITLE
Q: How to use?

### ISSUE THREAD

**Issue by KingKnecht** [michaelcheers/TypescriptToCS2#2]
Hi,
I have converted a TypeScript file with your tool. It produces something like:
```
System.Double this [System.Double index]
		{
			[Template("{this}[{index}]")]
			get;
			[Template("{this}[{index}]")]
			set;
		}
```

But I don't understand what to do next with this code? 
Thx,
Sven

**Comment by michaelcheers** [comment]
This code is now Bridge code. You can install bridge and use the code file generated. Then you can call the members like you would a bit like you would in javascript. If you send me the file, I can walk you through, on how to use it. The interaction is a bit different than it is in Javascript.

Steps to use:
1) create a class library in visual studio
2) go to the package manager console and run
```
Install-Package Bridge -Version 16.3.1
```
3) copy .d.cs file into the project.
4) write code in the main of Program.cs

@KingKnecht

**Comment by mwherman2000** [comment]
Do clarify... TypeScript2CS2 doesn't do a full translation of TS source into C# source? I was hoping it would.

**Comment by michaelcheers** [comment]
@mwherman2000, this project is now replaced by Retyped. It only provides a conversion of the type definitions of the typescript. It converts those to c#, to be used in c# projects for Bridge.
