### ISSUE TITLE
Is there a spritual succsessor to this?

### ISSUE THREAD

**Issue by jabba2324** [michaelcheers/TypescriptToCS2#3]
I've just had a look over Retyped and its focus seems more geared towards porting node packages to .net. Is there a successor to this or a more recently maintained project that you know of for compiling/transpiling typescript to C#?

**Comment by thales-man** [comment]
successor...
let's actually pray for something that works...

**Comment by michaelcheers** [comment]
This is a project I worked on a while back with a goal something like what you seem to want.  https://github.com/michaelcheers/JavaScriptToBridgeCS

It is nowhere near being useful for production use but possibly you could fork it and use it as a starting point.
